# https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html

liip_imagine:

    driver: "gd"
    default_filter_set_settings:
        format: webp
        
    webp:
        generate: true
        quality: 80    

    filter_sets:
        portrait: 
            filters: 
                thumbnail: { size: [300, 200], mode: outbound } 
                


